# Generated by Django 3.1.6 on 2021-03-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(auto_now_add=True, null=True, verbose_name='time')),
                ('coa', models.IntegerField(null=True, verbose_name='coa')),
                ('user', models.IntegerField(null=True, verbose_name='user')),
                ('img_before', models.CharField(max_length=255, null=True, verbose_name='img_before')),
                ('img_after', models.CharField(max_length=255, null=True, verbose_name='img_after')),
            ],
        ),
    ]
