# Generated by Django 3.1.6 on 2021-02-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, null=True, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, null=True, unique=True, verbose_name='username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('suspended_start_date', models.DateField(null=True, verbose_name='suspend start date')),
                ('suspended_end_date', models.DateField(null=True, verbose_name='suspend end date')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='last name')),
                ('date_of_birth', models.DateField(null=True, verbose_name='date of birth')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
