# Generated by Django 3.1.6 on 2021-03-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('coa', models.IntegerField(null=True, verbose_name='coa')),
                ('debit', models.FloatField(default=0.0, null=True, verbose_name='amount')),
                ('credit', models.FloatField(default=0.0, null=True, verbose_name='amount')),
                ('amount', models.FloatField(default=0.0, null=True, verbose_name='amount')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='date')),
                ('source', models.CharField(max_length=255, null=True, verbose_name='source')),
            ],
        ),
    ]
