# Generated by Django 3.1.6 on 2021-03-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='credit',
            field=models.FloatField(default=0.0, null=True, verbose_name='credit'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='debit',
            field=models.FloatField(default=0.0, null=True, verbose_name='debit'),
        ),
    ]
