# Generated by Django 3.1.6 on 2021-03-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20210331_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.IntegerField(default=True, verbose_name='status'),
        ),
    ]
