# Generated by Django 3.1.6 on 2021-03-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_journal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='comment',
            field=models.CharField(max_length=255, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='user',
            field=models.IntegerField(null=True, verbose_name='user'),
        ),
    ]
