# Generated by Django 3.1.6 on 2021-04-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_auto_20210331_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='file_upload',
            field=models.CharField(max_length=255, null=True, verbose_name='file_upload'),
        ),
    ]
