# Generated by Django 3.1.6 on 2021-02-09 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('dob', models.DateField(verbose_name='dob')),
                ('address', models.CharField(max_length=255, verbose_name='first_name')),
                ('user_img', models.CharField(max_length=255, verbose_name='first_name')),
                ('staff', models.BooleanField(default=True, verbose_name='staff')),
                ('manager', models.BooleanField(default=False, verbose_name='manager')),
                ('admin', models.BooleanField(default=False, verbose_name='admin')),
                ('password_created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='password_created_date')),
                ('suspension_start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='suspension_start_date')),
                ('suspension_end_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='suspension_end_date')),
            ],
        ),
    ]
