# Generated by Django 3.1.6 on 2021-02-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('dob', models.DateField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('staff', models.BooleanField(default=True)),
                ('manager', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
