# Generated by Django 3.1.6 on 2021-02-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager',
            field=models.BooleanField(default=False, verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=True, verbose_name='staff'),
        ),
    ]
