# Generated by Django 3.1.6 on 2021-02-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('number', models.CharField(max_length=30, null=True, unique=True, verbose_name='number')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='description')),
                ('normal_side', models.CharField(max_length=255, null=True, verbose_name='normal_side')),
                ('category', models.CharField(max_length=255, null=True, verbose_name='category')),
                ('subcategory', models.CharField(max_length=255, null=True, verbose_name='subcategory')),
                ('initial_balance', models.FloatField(default=0.0, null=True, verbose_name='initial balance')),
                ('debit', models.FloatField(default=0.0, null=True, verbose_name='debit')),
                ('credit', models.FloatField(default=0.0, null=True, verbose_name='credit')),
                ('balance', models.FloatField(default=0.0, null=True, verbose_name='balance')),
                ('date_added', models.DateField(auto_now_add=True, null=True, verbose_name='date joined')),
                ('user_id', models.IntegerField(null=True, verbose_name='user_id')),
                ('order', models.CharField(max_length=255, null=True, verbose_name='order')),
                ('statement', models.CharField(max_length=10, null=True, verbose_name='statement')),
            ],
        ),
    ]
